books/urls.py
from django.urls import path
from .views import book_list, make_payment, initiate_payment
app_name = "books"
urlpatterns = [
    path("", book_list, name="books"),
    path("payment/", initiate_payment, name="initiate_payment"),
    path('<int:id>/payment', make_payment, name="make_payment"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts.views import MainView, export

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", MainView.as_view(), name="index"),
    path('<str:format>/export', export, name="export"),
    path('books/', include('books.urls')),
    path("unicorn/", include("django_unicorn.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    publication_date = models.DateField()
    cover_image = models.ImageField(upload_to='book_covers/')

    def __str__(self):
        return self.title


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order #{self.id}"

    @property
    def total_price(self):
        return self.quantity * self.book.price

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    liked = models.ManyToManyField(User, related_name="liked")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"post {self.id}"

accounts/views.py
from django.shortcuts import render

# Create your views here.

books/views.py
import time
from paynow import Paynow
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Book, Order
from django.contrib.auth.decorators import login_required


@login_required
def book_list(request):
    books = Book.objects.all()
    print(books)
    context = {
        "books": books
    }
    return render(request, "books/main.html", context)


def initiate_payment(request):
    # Paynow API details (replace with your actual Paynow API details)
    return_url = 'http://localhost/payment/callback'  # Replace with your callback URL

    # Initialize Paynow
    paynow = Paynow(settings.PAYNOW_INTEGRATION_ID,
                    settings.PAYNOW_INTEGRATION_KEY, return_url, return_url)

    # Create a payment
    payment = paynow.create_payment('Order #100', 'test@example.com')

    # Add items to the payment
    payment.add('Bananas', 2.50)
    payment.add('Apples', 3.40)

    # Send the payment to Paynow
    response = paynow.send(payment)

    if response.success:
        # Get the link to redirect the user to Paynow's payment page
        link = response.redirect_url

        # Get the poll URL (used to check the status of a transaction)
        poll_url = response.poll_url

        status = paynow.check_transaction_status(poll_url)
        time.sleep(300)
        print(f"status {status}")
        # Store the poll URL in your database or session for later use
        request.session['poll_url'] = poll_url

        # Redirect the user to Paynow's payment page
        return redirect(link)
    else:
        # Handle the case where payment initiation failed
        return HttpResponse("error")


def make_payment(request, id):
    book = get_object_or_404(Book, pk=id)
    paynow = Paynow(
        settings.PAYNOW_INTEGRATION_ID,
        settings.PAYNOW_INTEGRATION_KEY,
        'http://localhost:8000/books/return/',
        'http://localhost:8000/books/result/'
    )
    payment = paynow.create_payment(f'Order #{id}', 'test@example.com')
    # Passing in the name of the item and the price of the item
    payment.add('Bananas', 2.50)
    payment.add('Apples', 3.40)
    # Save the response from Paynow in a variable
    response = paynow.send(payment)
    print(response)
    if response.success:
        # Get the link to redirect the user to, then use it as you see fit
        link = response.redirect_url

        # Get the poll URL (used to check the status of a transaction). You might want to save this in your DB
        poll_url = response.poll_url
        print(f'Poll url {poll_url}')
        return redirect(link)
    else:
        return HttpResponse("The payment failed: " + response.error())

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import HttpResponse
from .models import Post
from .admin import PostResource


class MainView(ListView):
    template_name = "posts/index.html"
    queryset = Post.objects.all()


def export(request, format):
    posts_resource = PostResource()
    dataset = posts_resource.export()
    if format == "csv":
        data_format = dataset.csv
    else:
        data_format = dataset.xls
    response = HttpResponse(data_format, content_type=f"text/{format}")
    response["Content-Disposition"] = f"attachment; filename=posts.{format}"
    return response

books/templates/books/main.html
{% extends 'base.html' %} {% load unicorn %}
<!--Block content -->
{% block content %} {% unicorn 'cart' user=request.user.pk books=books %}
<!-- close the block content -->
{% endblock content %}

books/templates/unicorn/cart.html
<div>
  <div class="grid grid-cols-3 gap-4 m-12">
    <div class="col-span-2" id="books">
      <h3 class="text-3xl mb-3">Available books</h3>
      {% for book in books %}
      <div class="max-w-sm rounded overflow-hidden shadow-lg my-3">
        <img
          class="w-full"
          src="{{book.cover_image.url}}"
          alt="Sunset in the mountains"
        />
        <div class="px-6 py-4">
          <div class="font-bold text-xl mb-2">{{ book.title}}</div>
          <p class="text-gray-700 text-base">{{ book.description}}</p>
        </div>
        <div class="px-6 pt-4 pb-2">
          <button
            unicorn:click="add_book({{book.id}})"
            class="bg-teal-700 text-white p-2 rounded"
          >
            Add to cart
          </button>
        </div>
        <a href="{% url 'books:make_payment' book.id %}">Pay</a>
      </div>
      {% endfor %}
    </div>
    <div>
      <h3 class="text-2xl text-center">Cart</h3>
      <div>
        {% if user_books %} {% for book in user_books %}
        <div>
          <span
            >{{book.quantity}} * {{ book.book.title }} -
            <span>{{ book.total_price}}</span></span
          ><i
            unicorn:click="delete_book({{book.id}})"
            class="fa-solid fa-trash text-red-600"
          ></i>
        </div>
        <!---->{% endfor %}
        <div class="mt-2 border-t-2">
          <div class="mt-2 flex justify-between">
            <p>Total Price</p>
            <p>{{total }}</p>
          </div>
        </div>
        {% else %}
        <span>There are no books in this cart</span>
        {% endif %}
      </div>
    </div>
  </div>
</div>

posts/templates/posts/index.html
{% extends "base.html" %} {% block title %} Home {% endblock title %}
<!---->{% block content %}
<div class="flex justify-between">
  <a href="{% url 'export' 'csv' %}" class="text-teal-500 bg-black p-2 rounded"
    >Export to csv
  </a>
  <a href="{% url 'export' 'xls' %}" class="text-teal-500 bg-black p-2 rounded"
    >Export to xls
  </a>
</div>
{% endblock content %}

templates/base.html
{% load unicorn %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <title>{% block title %} {% endblock title %}</title>
    {% unicorn_scripts %}
  </head>
  <body>
    {% csrf_token %}
    <div class="mt-5 max-w-[1024px] mx-auto shadow p-10 rounded">
      {% block content %} {% endblock content %}
    </div>
  </body>
</html>